---
title: RAQSAPI - Acknowledgements
author: Clinton Mccrowey physical scientist - US EPA
output:
  rmarkdown::html_vignette: default
  md_document:
    variant: gfm
lang: en-US
vignette: >
  %\VignetteIndexEntry{RAQSAPI - Acknowledgements}
  %\VignetteEncoding{UTF-8}
  %\VignetteDepends{knitr}
  %\VignetteDepends{rmarkdown}
  %\VignetteEngine{knitr::rmarkdown}
bibliography: AQSAPI.bib
csl: acs-nano.csl
---

# Acknowledgements
RAQSAPI was included in the Rblogger's  March 2021: “Top 40” [New CRAN Packages](https://www.r-bloggers.com/2021/04/march-2021-top-40-new-cran-packages/).

  The RAQSAPI package borrows upon functions and code provided by sources not
mentioned in the DESCRIPTION file. Here we attempt to acknowledge those sources
without them RAQSAPI would not be possible.

* README badges are provided by R package `badgecreator`[@package:badgecreatr].
* The R package `usethis`[@package:usethis] was used to generate GitHub actions
    for Continuous integration (CI).
* Code cleanup was assisted by the R package `lintr`[@package:lintr]
* the function *install.packages* are provided by the R package `utils`[@RBase]
* the function *install_github* are provided by the R package `remotes`[
    @package:remotes]
* .gitignore file borrowed examples from
     https://github.com/github/gitignore/blob/master/R.gitignore
* . CITATION.cff file was generated by the R package `cffr` [@package:cffr]
* R package `urlchecker` [@package:urlchecker] was used to check urls in RAQSAPI
    documentation
* R package `goodpractice` [@package:goodpractice] was used for static code checking
* R package `formatR` [@package:formatR] was used to form code in this repository
* R package `testthat` [@package:testthat] is used for unit testing
  * unit tests are mocked using R package `httptest2` [@package:httptest2]
  
  Additionally the project maintainers would like to thank the following people:
  Cynthia Sthal, Maria Morresi both at the US Environmental Protection Agency and
  Hayley Brittingham at Neptune and Company for their assistance with improving the
  package documentation. This is a huge undertaking, documentation is often overlooked
  and not given proper attention to. We thank you for your efforts.
