---
title: RAQSAPI - Install and Setup
author:
- affiliation: |-
    United States Environmental Protection Agency (US EPA),  
        Region III,  
        Air and Radiation Division,  
        Air Quality and Analysis Branch
  name: Clinton Mccrowey
output:
  rmarkdown::html_vignette: default
  md_document:
    variant: gfm
vignette: >
  %\VignetteIndexEntry{RAQSAPI - Install and Setup}
  %\VignetteEncoding{UTF-8}
  %\VignetteDepends{knitr}
  %\VignetteDepends{rmarkdown}
  %\VignetteEngine{knitr::rmarkdown}
---

# Installing RAQSAPI

Either install the stable version from CRAN or install the latest development version from GitHub.

## Option 1: Installing the stable version from CRAN (preferred method)
First install the `pak` packages if not already installed
``` r
install.packages("pak", dependencies = TRUE)
```
Then use the package `pak` to install the latest stable version of RAQSAPI from CRAN
``` r
pak::pkg_install(pkgs="RAQSAPI", dependencies = TRUE)
```

## Option 2: Installing the development version of RAQSAPI (unstable)

> [!CAUTION] The development version of RAQSAPI contains code that has not yet been thoroughly been tested and is more likely to contain bugs. It is recommended that the stable CRAN version be installed for production use.

To install the development version of `RAQSAPI`, first if not already installed, install the `pak` package and its dependencies. Then run the following in a R environment.

``` r
pak::pkg_install("USEPA/RAQSAPI")
```
