library(httptest2)
source("helper.R")
httptest2::.mockPaths(c("./tests/testthat/",
  "./tests/testthat/bybox",
  "./tests/testthat/bycbsa",
  "./tests/testthat/byco",
  "./tests/testthat/byMA",
  "./tests/testthat/bypqao",
  "./tests/testthat/bysite",
  "./tests/testthat/bystate",
  "./tests/testthat/listfunctions"))
