---
name: pkgcheck

# This will cancel running jobs once a new run is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  workflow_run:
    workflows: ["R-CMD-check"]
    types: [completed]
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  pkgcheck:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - name: Find PR number
        id: pr
        run: |
          PR="${{ github.event.workflow_run.pull_requests[0].number }}"
          echo "pr=$PR" >> $GITHUB_OUTPUT
      - uses: ropensci-review-tools/pkgcheck-action@main
        with:
          issue-number: ${{ steps.pr.outputs.pr }}
          issue-title: "(Automated) pkgcheck report for ${{ github.repository }}"
          append-to-issue: true
          skip_checks: |
            - lintr_assignment_linter
